DROP VIEW IF EXISTS v_mitarbeiter_bestellstatus_uebersicht;
DROP VIEW IF EXISTS v_mitarbeiter_uebersicht;
DROP VIEW IF EXISTS v_produkt_verkaufszahlen;
DROP VIEW IF EXISTS v_kunde_summe_anzahl_bestellungen;

DROP TABLE IF EXISTS bestellposition CASCADE;
DROP TABLE IF EXISTS produkt CASCADE;
DROP TABLE IF EXISTS bestellung CASCADE;
DROP TABLE IF EXISTS mitarbeiter CASCADE;
DROP TABLE IF EXISTS kunde_hat_adressen CASCADE;
DROP TABLE IF EXISTS kunde CASCADE;
DROP TABLE IF EXISTS adresse CASCADE;

CREATE TABLE adresse (
    adresse_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aktiv BOOLEAN NOT NULL,
    strasse VARCHAR(60) NOT NULL CHECK (strasse ~ '^[A-ZÄÖÜ][a-zäöüß]*$'),
    hausnummer VARCHAR(10) NOT NULL CHECK (hausnummer ~ '^[0-9]+[a-z]?$'),
    plz NUMERIC(12,0) NOT NULL,
    ort VARCHAR(255) NOT NULL,
    land VARCHAR(255) NOT NULL
);

CREATE TABLE kunde (
    kunde_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(256) UNIQUE NOT NULL CHECK (email LIKE '%@%.%'),
    vorname VARCHAR(32) NOT NULL CHECK (vorname ~ '^[a-zA-ZäöüÄÖÜß]+$'),
    nachname VARCHAR(32) NOT NULL CHECK (nachname ~ '^[a-zA-ZäöüÄÖÜß]+$'),
    passwort VARCHAR(20) NOT NULL CHECK (
        LENGTH(passwort) BETWEEN 5 AND 20 AND
        passwort ~ '[0-9]' AND
        passwort ~ '[a-zA-Z]' AND
        passwort ~ '[^a-zA-Z0-9]'
    )
);

CREATE TABLE kunde_hat_adressen (
    adresse_id BIGINT REFERENCES adresse(adresse_id) ON DELETE CASCADE,
    kunde_id BIGINT REFERENCES kunde(kunde_id) ON DELETE CASCADE,
    typ VARCHAR(20) NOT NULL CHECK (typ IN ('Lieferadresse', 'Rechnungsadresse')),
    PRIMARY KEY (adresse_id, kunde_id)
);

CREATE TABLE mitarbeiter (
    personal_nr BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname VARCHAR(255) NOT NULL,
    nachname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    passwort VARCHAR(20) NOT NULL CHECK (
        LENGTH(passwort) BETWEEN 5 AND 20 AND
        passwort ~ '[0-9]' AND
        passwort ~ '[a-zA-Z]' AND
        passwort ~ '[^a-zA-Z0-9]'
    )
);

CREATE TABLE bestellung (
    bestellung_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kunde_id BIGINT REFERENCES kunde(kunde_id),
    mitarbeiterzuweis BIGINT REFERENCES mitarbeiter(personal_nr),
    datum TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('neu', 'bezahlt', 'versendet', 'abgeschlossen', 'storniert'))
);

CREATE TABLE produkt (
    sku VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    preis NUMERIC(10,2) NOT NULL,
    lagerbestand INTEGER NOT NULL CHECK (lagerbestand >= 0),
    angelegt_von BIGINT REFERENCES mitarbeiter(personal_nr)
);

CREATE TABLE bestellposition (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bestellung_id BIGINT REFERENCES bestellung(bestellung_id) ON DELETE CASCADE,
    sku VARCHAR(255) REFERENCES produkt(sku),
    menge INTEGER NOT NULL CHECK (menge > 0)
);

CREATE OR REPLACE FUNCTION check_bestellung_status_update() RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status NOT IN ('neu', 'bezahlt') AND NEW.status = 'storniert' THEN
        RAISE EXCEPTION 'Stornierung nur erlaubt, wenn Status neu oder bezahlt ist.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bestellung_check_status
BEFORE UPDATE ON bestellung
FOR EACH ROW EXECUTE FUNCTION check_bestellung_status_update();

CREATE OR REPLACE FUNCTION restore_stock_on_cancel() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'storniert' AND OLD.status != 'storniert' THEN
        UPDATE produkt p
        SET lagerbestand = lagerbestand + bp.menge
        FROM bestellposition bp
        WHERE bp.sku = p.sku AND bp.bestellung_id = NEW.bestellung_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_restore_stock_on_cancel
AFTER UPDATE ON bestellung
FOR EACH ROW EXECUTE FUNCTION restore_stock_on_cancel();

CREATE OR REPLACE FUNCTION manage_stock_on_position_change() RETURNS TRIGGER AS $$
DECLARE
    v_status VARCHAR;
    v_lagerbestand INTEGER;
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT status INTO v_status FROM bestellung WHERE bestellung_id = NEW.bestellung_id;
        IF v_status = 'storniert' THEN RETURN NEW; END IF;

        SELECT lagerbestand INTO v_lagerbestand FROM produkt WHERE sku = NEW.sku;
        IF v_lagerbestand < NEW.menge THEN
            RAISE EXCEPTION 'Nicht genug Lagerbestand.';
        END IF;

        UPDATE produkt SET lagerbestand = lagerbestand - NEW.menge WHERE sku = NEW.sku;
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        SELECT status INTO v_status FROM bestellung WHERE bestellung_id = NEW.bestellung_id;
        IF v_status = 'storniert' THEN RETURN NEW; END IF;

        SELECT lagerbestand INTO v_lagerbestand FROM produkt WHERE sku = NEW.sku;
        
        IF (v_lagerbestand + OLD.menge - NEW.menge) < 0 THEN
             RAISE EXCEPTION 'Nicht genug Lagerbestand für Erhöhung.';
        END IF;

        UPDATE produkt SET lagerbestand = lagerbestand + OLD.menge - NEW.menge WHERE sku = NEW.sku;
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        SELECT status INTO v_status FROM bestellung WHERE bestellung_id = OLD.bestellung_id;
        IF v_status = 'storniert' THEN RETURN OLD; END IF;

        UPDATE produkt SET lagerbestand = lagerbestand + OLD.menge WHERE sku = OLD.sku;
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bestellposition_change
BEFORE INSERT OR UPDATE OR DELETE ON bestellposition
FOR EACH ROW EXECUTE FUNCTION manage_stock_on_position_change();

CREATE VIEW v_kunde_summe_anzahl_bestellungen AS
SELECT 
    k.kunde_id AS "kundeId", 
    k.email, 
    COUNT(DISTINCT b.bestellung_id) AS "anzahlBestellungen",
    COALESCE(SUM(bp.menge * p.preis), 0) AS "gesamtsumme"
FROM kunde k
LEFT JOIN bestellung b ON k.kunde_id = b.kunde_id
LEFT JOIN bestellposition bp ON b.bestellung_id = bp.bestellung_id
LEFT JOIN produkt p ON bp.sku = p.sku
GROUP BY k.kunde_id, k.email
ORDER BY k.kunde_id ASC;

CREATE VIEW v_produkt_verkaufszahlen AS
SELECT 
    p.sku, 
    p.name, 
    COALESCE(SUM(bp.menge), 0) AS "gesamtVerkaufteMenge",
    COALESCE(SUM(CASE WHEN b.status NOT IN ('neu', 'storniert') THEN bp.menge * p.preis ELSE 0 END), 0) AS "umsatz",
    COUNT(DISTINCT b.bestellung_id) AS "anzahlBestellungen"
FROM produkt p
LEFT JOIN bestellposition bp ON p.sku = bp.sku
LEFT JOIN bestellung b ON bp.bestellung_id = b.bestellung_id
GROUP BY p.sku, p.name
ORDER BY "gesamtVerkaufteMenge" DESC;

CREATE VIEW v_mitarbeiter_uebersicht AS
SELECT 
    m.personal_nr AS "personalNr",
    (SELECT COUNT(*) FROM bestellung b WHERE b.mitarbeiterzuweis = m.personal_nr) AS "anzahlVerwalteterBestellungen",
    (SELECT COUNT(*) FROM produkt p WHERE p.angelegt_von = m.personal_nr) AS "anzahlAngelegterProdukte"
FROM mitarbeiter m
ORDER BY m.personal_nr ASC;

CREATE VIEW v_mitarbeiter_bestellstatus_uebersicht AS
SELECT 
    m.personal_nr AS "personalNr",
    s.status,
    COUNT(b.bestellung_id) AS "anzahlBestellungen"
FROM mitarbeiter m
CROSS JOIN (
    SELECT 'neu' as status UNION ALL 
    SELECT 'bezahlt' UNION ALL 
    SELECT 'versendet' UNION ALL 
    SELECT 'abgeschlossen' UNION ALL 
    SELECT 'storniert'
) s
LEFT JOIN bestellung b ON m.personal_nr = b.mitarbeiterzuweis AND b.status = s.status
GROUP BY m.personal_nr, s.status
ORDER BY m.personal_nr ASC, s.status ASC;